export const dicionarioPTEN: { [key: string]: string } = {
'olá': 'hello',
'mundo': 'world',
'como vai': 'how are you',
'estou bem': 'I am fine',
'parar gravação': 'stop recording',
'bom dia': 'good morning',
'boa tarde': 'good afternoon',
'boa noite': 'good evening',
'tchau': 'goodbye',
'por favor': 'please',
'obrigado': 'thank you',
'obrigada': 'thank you',
'desculpa': 'sorry',
'com licença': 'excuse me',
'sim': 'yes',
'não': 'no',
'talvez': 'maybe',
'eu não sei': 'I don\'t know',
'onde está o banheiro?': 'where is the bathroom?',
'quanto custa?': 'how much does it cost?',
'meu nome é': 'my name is',
'qual é o seu nome?': 'what is your name?',
'você fala inglês?': 'do you speak English?',
'eu falo um pouco de inglês': 'I speak a little English',
'por que?': 'why?',
'porque sim': 'because yes',
'como você está?': 'how are you?',
'estou cansado': 'I am tired',
'estou com fome': 'I am hungry',
'estou com sede': 'I am thirsty',
'eu preciso de ajuda': 'I need help',
'onde fica...?': 'where is...?',
'eu gosto de': 'I like',
'eu não gosto de': 'I don\'t like',
'eu quero': 'I want',
'eu preciso': 'I need',
'você pode me ajudar?': 'can you help me?',
'eu não entendi': 'I didn\'t understand',
'pode repetir?': 'can you repeat?',
'desculpe, não entendo': 'sorry, I don\'t understand',
'meu Deus!': 'my God!',
'que lindo!': 'how beautiful!',
'que bom!': 'that\'s great!',
'que chato!': 'that\'s boring!',
'isso é incrível!': 'that\'s amazing!',
'eu estou indo': 'I am going',
'vamos lá': 'let\'s go',
'espera aí': 'wait a second',
'cuidado!': 'careful!',
'não faça isso': 'don\'t do that',
'pode ser?': 'can it be?',
'eu não tenho dinheiro': 'I don\'t have money',
'eu não falo muito bem': 'I don\'t speak very well',
'você quer?': 'do you want?',
'nada': 'nothing',
'tudo bem': 'it\'s ok',
'está bem': 'it\'s fine',
'eu sou de': 'I am from',
'quanto tempo você vai ficar?': 'how long will you stay?',
'eu estou perdido': 'I am lost',
'me ajude, por favor': 'help me, please',
'alguém pode me ajudar?': 'can someone help me?',
'você está bem?': 'are you ok?',
'eu estou bem': 'I am fine',
'estou mal': 'I am not well',
'eu quero ir para casa': 'I want to go home',
'eu preciso descansar': 'I need to rest',
'estou esperando': 'I am waiting',
'eu sou brasileiro': 'I am Brazilian',
'eu sou americana': 'I am American',
'você é meu amigo': 'you are my friend',
'vamos conversar': 'let\'s talk',
'de onde você é?': 'where are you from?',
'qual a sua idade?': 'how old are you?',
'eu tenho 25 anos': 'I am 25 years old',
'você gosta disso?': 'do you like this?',
'eu adoro isso': 'I love this',
'eu detesto isso': 'I hate this',
'o que você está fazendo?': 'what are you doing?',
'o que aconteceu?': 'what happened?',
'onde você vai?': 'where are you going?',
'eu vou para a escola': 'I am going to school',
'eu vou para o trabalho': 'I am going to work',
'você está com fome?': 'are you hungry?',
'onde podemos comer?': 'where can we eat?',
'eu sou vegetariano': 'I am vegetarian',
'eu sou vegano': 'I am vegan',
'qual é a sua comida favorita?': 'what is your favorite food?',
'meu prato favorito é': 'my favorite dish is',
'eu amo pizza': 'I love pizza',
'estou assistindo TV': 'I am watching TV',
'qual é o seu hobby?': 'what is your hobby?',
'meu hobby é ler': 'my hobby is reading',
'você gosta de música?': 'do you like music?',
'eu adoro música': 'I love music',
'qual é o seu filme favorito?': 'what is your favorite movie?',
'você gosta de viajar?': 'do you like to travel?',
'eu amo viajar': 'I love to travel',
'estou aprendendo inglês': 'I am learning English',
'você pode me ensinar?': 'can you teach me?',
'estou cansado de esperar': 'I am tired of waiting',
'não tenho tempo': 'I don\'t have time',
'preciso ir agora': 'I need to go now',
'até logo': 'see you later',
'nos vemos em breve': 'see you soon',
'adeus': 'goodbye',
'bom trabalho': 'good job',
'feliz aniversário': 'happy birthday',
'feliz ano novo': 'happy new year',
'boas festas': 'happy holidays',
'boa sorte': 'good luck',
'divirta-se': 'have fun',
'tenha um bom dia': 'have a nice day',
'estou com saudade': 'I miss you',
'eu preciso de um médico': 'I need a doctor',
'eu não me sinto bem': 'I don\'t feel well',
'você tem algum problema?': 'do you have any problem?',
'estou com dor de cabeça': 'I have a headache',
'estou com dor nas costas': 'I have a back pain',
'estou gripado': 'I have a cold',
'eu tenho febre': 'I have a fever',
'você pode me ajudar com isso?': 'can you help me with this?',
'onde fica o hospital?': 'where is the hospital?',
'eu vou chamar uma ambulância': 'I will call an ambulance',
'chame um médico': 'call a doctor',
'me dê um remédio': 'give me some medicine',
'estou indo para o trabalho': 'I am going to work',
'estou indo para a escola': 'I am going to school',
'hoje é um dia bonito': 'today is a beautiful day',
'a noite está fria': 'the night is cold',
'o sol está brilhando': 'the sun is shining',
'está chovendo': 'it\'s raining',
'está nevando': 'it\'s snowing',
'está ventando': 'it\'s windy',
'não tenho mais dinheiro': 'I don\'t have money anymore',
'preciso ir ao supermercado': 'I need to go to the supermarket',
'o que você está pensando?': 'what are you thinking?',
'você está com raiva?': 'are you angry?',
'estou feliz': 'I am happy',
'estou triste': 'I am sad',
'estou com medo': 'I am scared',
'estou nervoso': 'I am nervous',
'estou animado': 'I am excited',
'estou entediado': 'I am bored',
'eu adoro esse lugar': 'I love this place',
'eu não gosto desse lugar': 'I don\'t like this place',
'estou muito ocupado': 'I am very busy',
'não estou com pressa': 'I am not in a hurry',
'estou esperando alguém': 'I am waiting for someone',
'eu tenho uma reunião': 'I have a meeting',
'eu estou trabalhando': 'I am working',
'eu preciso de um café': 'I need a coffee',
'você tem café?': 'do you have coffee?',
'eu prefiro chá': 'I prefer tea',
'você gosta de café?': 'do you like coffee?',
'me passe o sal': 'pass me the salt',
'me passe o açúcar': 'pass me the sugar',
'me passa um copo de água': 'pass me a glass of water',
'onde posso comprar isso?': 'where can I buy this?',
'quanto custa isso?': 'how much does it cost?',
'tem desconto?': 'is there a discount?',
'eu quero comprar isso': 'I want to buy this',
'isso é muito caro': 'this is very expensive',
'isso é barato': 'this is cheap',
'tem mais barato?': 'is there anything cheaper?',
'isso está em promoção?': 'is it on sale?'
};

export const dicionarioENES: { [key: string]: string } = {
'hola': 'hello',
'mundo': 'world',
'cómo va': 'how are you',
'estoy bien': 'I am fine',
'parar grabación': 'stop recording',
'buenos días': 'good morning',
'buenas tardes': 'good afternoon',
'buenas noches': 'good evening',
'adiós': 'goodbye',
'por favor': 'please',
'gracias': 'thank you',
'perdón': 'sorry',
'con permiso': 'excuse me',
'sí': 'yes',
'no': 'no',
'tal vez': 'maybe',
'no sé': 'I don\'t know',
'dónde está el baño?': 'where is the bathroom?',
'¿cuánto cuesta?': 'how much does it cost?',
'mi nombre es': 'my name is',
'¿cuál es tu nombre?': 'what is your name?',
'hablas inglés?': 'do you speak English?',
'hablo un poco de inglés': 'I speak a little English',
'¿por qué?': 'why?',
'porque sí': 'because yes',
'cómo estás?': 'how are you?',
'estoy cansado': 'I am tired',
'tengo hambre': 'I am hungry',
'tengo sed': 'I am thirsty',
'necesito ayuda': 'I need help',
'dónde está...?': 'where is...?',
'me gusta': 'I like',
'no me gusta': 'I don\'t like',
'quiero': 'I want',
'necesito': 'I need',
'me puedes ayudar?': 'can you help me?',
'no entendí': 'I didn\'t understand',
'puedes repetir?': 'can you repeat?',
'disculpa, no entiendo': 'sorry, I don\'t understand',
'¡Dios mío!': 'my God!',
'¡qué bonito!': 'how beautiful!',
'¡qué bien!': 'that\'s great!',
'¡qué aburrido!': 'that\'s boring!',
'¡eso es increíble!': 'that\'s amazing!',
'me voy': 'I am going',
'vamos': 'let\'s go',
'espera un momento': 'wait a second',
'cuidado!': 'careful!',
'no hagas eso': 'don\'t do that',
'puede ser?': 'can it be?',
'no tengo dinero': 'I don\'t have money',
'no hablo muy bien': 'I don\'t speak very well',
'¿quieres?': 'do you want?',
'nada': 'nothing',
'está bien': 'it\'s ok',
'todo bien': 'it\'s fine',
'soy de': 'I am from',
'¿cuánto tiempo vas a estar?': 'how long will you stay?',
'estoy perdido': 'I am lost',
'me ayudas por favor': 'help me, please',
'¿alguien puede ayudarme?': 'can someone help me?',
'¿estás bien?': 'are you ok?',
'no me encuentro bien': 'I am not feeling well',
'quiero ir a casa': 'I want to go home',
'necesito descansar': 'I need to rest',
'estoy esperando': 'I am waiting',
'soy mexicano': 'I am Mexican',
'soy americano': 'I am American',
'eres mi amigo': 'you are my friend',
'vamos a hablar': 'let\'s talk',
'¿de dónde eres?': 'where are you from?',
'¿cuántos años tienes?': 'how old are you?',
'tengo 25 años': 'I am 25 years old',
'¿te gusta esto?': 'do you like this?',
'me encanta esto': 'I love this',
'odio esto': 'I hate this',
'¿qué estás haciendo?': 'what are you doing?',
'¿qué pasó?': 'what happened?',
'¿dónde vas?': 'where are you going?',
'voy a la escuela': 'I am going to school',
'voy al trabajo': 'I am going to work',
'¿tienes hambre?': 'are you hungry?',
'¿dónde podemos comer?': 'where can we eat?',
'soy vegetariano': 'I am vegetarian',
'soy vegano': 'I am vegan',
'¿cuál es tu comida favorita?': 'what is your favorite food?',
'mi comida favorita es': 'my favorite food is',
'me encanta la pizza': 'I love pizza',
'estoy viendo la televisión': 'I am watching TV',
'¿cuál es tu pasatiempo?': 'what is your hobby?',
'mi pasatiempo es leer': 'my hobby is reading',
'¿te gusta la música?': 'do you like music?',
'me encanta la música': 'I love music',
'¿cuál es tu película favorita?': 'what is your favorite movie?',
'¿te gusta viajar?': 'do you like to travel?',
'me encanta viajar': 'I love to travel',
'estoy aprendiendo inglés': 'I am learning English',
'¿puedes enseñarme?': 'can you teach me?',
'estoy cansado de esperar': 'I am tired of waiting',
'no tengo tiempo': 'I don\'t have time',
'tengo que ir ahora': 'I need to go now',
'hasta luego': 'see you later',
'nos vemos pronto': 'see you soon',
'buen trabajo': 'good job',
'feliz cumpleaños': 'happy birthday',
'feliz año nuevo': 'happy new year',
'felices fiestas': 'happy holidays',
'buena suerte': 'good luck',
'diviértete': 'have fun',
'que tengas un buen día': 'have a nice day',
'te extraño': 'I miss you',
'necesito un médico': 'I need a doctor',
'no me siento bien': 'I don\'t feel well',
'¿tienes algún problema?': 'do you have any problem?',
'tengo dolor de cabeza': 'I have a headache',
'me duele la espalda': 'I have a back pain',
'estoy resfriado': 'I have a cold',
'tengo fiebre': 'I have a fever',
'puedes ayudarme con esto?': 'can you help me with this?',
'¿dónde está el hospital?': 'where is the hospital?',
'voy a llamar una ambulancia': 'I will call an ambulance',
'llama a un médico': 'call a doctor',
'dame un medicamento': 'give me some medicine',
'hoy es un día bonito': 'today is a beautiful day',
'la noche está fría': 'the night is cold',
'el sol está brillando': 'the sun is shining',
'está lloviendo': 'it\'s raining',
'está nevando': 'it\'s snowing',
'está ventoso': 'it\'s windy',
'ya no tengo dinero': 'I don\'t have money anymore',
'necesito ir al supermercado': 'I need to go to the supermarket',
'¿qué estás pensando?': 'what are you thinking?',
'¿estás enojado?': 'are you angry?',
'estoy feliz': 'I am happy',
'estoy triste': 'I am sad',
'tengo miedo': 'I am scared',
'estoy nervioso': 'I am nervous',
'estoy emocionado': 'I am excited',
'estoy aburrido': 'I am bored',
'me encanta este lugar': 'I love this place',
'no me gusta este lugar': 'I don\'t like this place',
'estoy muy ocupado': 'I am very busy',
'no tengo prisa': 'I am not in a hurry',
'estoy esperando a alguien': 'I am waiting for someone',
'tengo una reunión': 'I have a meeting',
'estoy trabajando': 'I am working',
'necesito un café': 'I need a coffee',
'¿tienes café?': 'do you have coffee?',
'prefiero té': 'I prefer tea',
'¿te gusta el café?': 'do you like coffee?',
'pásame la sal': 'pass me the salt',
'pásame el azúcar': 'pass me the sugar',
'dame un vaso de agua': 'give me a glass of water',
'me pasa un vaso de jugo': 'pass me a glass of juice',
'¿dónde puedo comprar esto?': 'where can I buy this?',
'¿cuánto cuesta esto?': 'how much does this cost?',
'¿hay descuento?': 'is there a discount?',
'quiero comprar esto': 'I want to buy this',
'esto es muy caro': 'this is very expensive',
'esto está barato': 'this is cheap',
'hay algo más barato?': 'is there something cheaper?',
'está en oferta?': 'is it on sale?'
};

export const dicionarioPTES: { [key: string]: string } = {
'olá': 'hola',
'mundo': 'mundo',
'como vai': 'cómo va',
'estou bem': 'estoy bien',
'parar gravação': 'parar grabación',
'bom dia': 'buenos días',
'boa tarde': 'buenas tardes',
'boa noite': 'buenas noches',
'adeus': 'adiós',
'por favor': 'por favor',
'obrigado': 'gracias',
'desculpe': 'perdón',
'com licença': 'con permiso',
'sim': 'sí',
'não': 'no',
'talvez': 'tal vez',
'não sei': 'no sé',
'onde está o banheiro?': '¿dónde está el baño?',
'quanto custa?': '¿cuánto cuesta?',
'meu nome é': 'mi nombre es',
'qual é o seu nome?': '¿cuál es tu nombre?',
'você fala inglês?': '¿hablas inglés?',
'eu falo um pouco de inglês': 'hablo un poco de inglés',
'porque sim': 'porque sí',
'não entendi': 'no entendí',
'pode repetir?': '¿puedes repetir?',
'desculpa, não entendi': 'disculpa, no entiendo',
'estou cansado': 'estoy cansado',
'estou com fome': 'tengo hambre',
'estou com sede': 'tengo sed',
'preciso de ajuda': 'necesito ayuda',
'onde está...?': '¿dónde está...?',
'eu gosto de': 'me gusta',
'não gosto de': 'no me gusta',
'quero': 'quiero',
'preciso': 'necesito',
'você pode me ajudar?': '¿me puedes ayudar?',
'você pode repetir?': '¿puedes repetir?',
'eu estou esperando': 'estoy esperando',
'sou brasileiro': 'soy brasileño',
'sou argentino': 'soy argentino',
'vamos': 'vamos',
'espere um momento': 'espera un momento',
'cuidado!': '¡cuidado!',
'não faça isso': 'no hagas eso',
'pode ser?': '¿puede ser?',
'não tenho dinheiro': 'no tengo dinero',
'onde podemos comer?': '¿dónde podemos comer?',
'eu sou vegetariano': 'soy vegetariano',
'você gosta de música?': '¿te gusta la música?',
'gosto de viajar': 'me gusta viajar',
'estou aprendendo espanhol': 'estoy aprendiendo español',
'você pode me ensinar?': '¿me puedes enseñar?',
'estou cansado de esperar': 'estoy cansado de esperar',
'não tenho tempo': 'no tengo tiempo',
'preciso ir agora': 'necesito ir ahora',
'até logo': 'hasta luego',
'nos vemos em breve': 'nos vemos pronto',
'feliz aniversário': 'feliz cumpleaños',
'feliz ano novo': 'feliz año nuevo',
'boas festas': 'felices fiestas',
'boa sorte': 'buena suerte',
'divirta-se': 'diviértete',
'tenha um bom dia': 'que tengas un buen día',
'sinto sua falta': 'te extraño',
'você está bem?': '¿estás bien?',
'preciso de um médico': 'necesito un médico',
'não estou me sentindo bem': 'no me siento bien',
'você tem algum problema?': '¿tienes algún problema?',
'estou perdido': 'estoy perdido',
'preciso de um café': 'necesito un café',
'você tem café?': '¿tienes café?',
'eu prefiro chá': 'prefiero té',
'passe-me o sal': 'pásame la sal',
'passe-me o açúcar': 'pásame el azúcar',
'me dá um copo de água': 'dame un vaso de agua',
'onde posso comprar isso?': '¿dónde puedo comprar esto?',
'quanto custa isso?': '¿cuánto cuesta esto?',
'está em promoção?': '¿está en oferta?',
'quero comprar isso': 'quiero comprar esto',
'isso é muito caro': 'esto es muy caro',
'isso está barato': 'esto está barato',
'tem algo mais barato?': '¿hay algo más barato?',
'está em oferta?': '¿está en oferta?',
'isso é incrível!': '¡esto es increíble!',
'o que você está fazendo?': '¿qué estás haciendo?',
'o que aconteceu?': '¿qué pasó?',
'onde você vai?': '¿dónde vas?',
'eu vou para a escola': 'voy a la escuela',
'eu vou para o trabalho': 'voy al trabajo',
'estou esperando alguém': 'estoy esperando a alguien',
'qual é a sua comida favorita?': '¿cuál es tu comida favorita?',
'minha comida favorita é': 'mi comida favorita es',
'eu adoro pizza': 'me encanta la pizza',
'estou assistindo TV': 'estoy viendo la televisión',
'qual é o seu passatempo?': '¿cuál es tu pasatiempo?',
'meu passatempo é ler': 'mi pasatiempo es leer',
'você gosta de viajar?': '¿te gusta viajar?',
'eu adoro viajar': 'me encanta viajar',
'estou aprendendo inglês': 'estoy aprendiendo inglés',
'não tenho prisa': 'no tengo prisa',
'eu estou muito ocupado': 'estoy muy ocupado',
'eu preciso de descanso': 'necesito descansar',
'eu estou perdido': 'estoy perdido',
'me ajuda por favor': 'ayúdame por favor',
'me passa um copo de água': 'pásame un vaso de agua',
'você quer?': '¿quieres?',
'não entendi o que você disse': 'no entendí lo que dijiste',
'pode me ensinar mais?': '¿puedes enseñarme más?',
'eu não tenho tempo': 'no tengo tiempo',
'estou esperando a minha vez': 'estoy esperando mi turno',
'onde podemos nos encontrar?': '¿dónde podemos encontrarnos?',
'você gosta de futebol?': '¿te gusta el fútbol?',
'gostei muito!': '¡me gustó mucho!',
'me avise quando chegar': 'avísame cuando llegues',
'onde fica o supermercado?': '¿dónde está el supermercado?',
'eu estou indo para a casa': 'estoy yendo a casa',
'você está com fome?': '¿tienes hambre?',
'você está com sede?': '¿tienes sed?',
'eu vou para o trabalho agora': 'voy al trabajo ahora',
};

export const dicionarioPTFR: { [key: string]: string } = {
'olá': 'bonjour',
'mundo': 'monde',
'como vai': 'comment ça va',
'estou bem': 'je vais bien',
'parar gravação': 'arrêter l\'enregistrement',
'bom dia': 'bonjour',
'boa tarde': 'bon après-midi',
'boa noite': 'bonne nuit',
'adeus': 'au revoir',
'por favor': 's\'il vous plaît',
'obrigado': 'merci',
'desculpe': 'désolé',
'com licença': 'excusez-moi',
'sim': 'oui',
'não': 'non',
'talvez': 'peut-être',
'não sei': 'je ne sais pas',
'onde está o banheiro?': 'où sont les toilettes?',
'quanto custa?': 'combien ça coûte?',
'meu nome é': 'mon nom est',
'qual é o seu nome?': 'quel est votre nom?',
'você fala inglês?': 'parlez-vous anglais?',
'eu falo um pouco de inglês': 'je parle un peu anglais',
'porque sim': 'parce que oui',
'não entendi': 'je n\'ai pas compris',
'pode repetir?': 'pouvez-vous répéter?',
'desculpa, não entendi': 'désolé, je n\'ai pas compris',
'estou cansado': 'je suis fatigué',
'estou com fome': 'j\'ai faim',
'estou com sede': 'j\'ai soif',
'preciso de ajuda': 'j\'ai besoin d\'aide',
'onde está...?': 'où est... ?',
'eu gosto de': 'j\'aime',
'não gosto de': 'je n\'aime pas',
'quero': 'je veux',
'preciso': 'j\'ai besoin',
'você pode me ajudar?': 'vous pouvez m\'aider?',
'você pode repetir?': 'pouvez-vous répéter?',
'eu estou esperando': 'j\'attends',
'sou brasileiro': 'je suis brésilien',
'sou argentino': 'je suis argentin',
'vamos': 'allons',
'espere um momento': 'attendez un moment',
'cuidado!': 'attention!',
'não faça isso': 'ne faites pas ça',
'pode ser?': 'ça peut être?',
'não tenho dinheiro': 'je n\'ai pas d\'argent',
'onde podemos comer?': 'où pouvons-nous manger?',
'eu sou vegetariano': 'je suis végétarien',
'você gosta de música?': 'aimez-vous la musique?',
'gosto de viajar': 'j\'aime voyager',
'estou aprendendo francês': 'j\'apprends le français',
'você pode me ensinar?': 'vous pouvez m\'enseigner?',
'estou cansado de esperar': 'je suis fatigué d\'attendre',
'não tenho tempo': 'je n\'ai pas le temps',
'preciso ir agora': 'je dois y aller maintenant',
'até logo': 'à bientôt',
'nos vemos em breve': 'à bientôt',
'feliz aniversário': 'joyeux anniversaire',
'feliz ano novo': 'bonne année',
'boas festas': 'joyeuses fêtes',
'boa sorte': 'bonne chance',
'divirta-se': 'amusez-vous',
'tenha um bom dia': 'bonne journée',
'sinto sua falta': 'tu me manques',
'você está bem?': 'ça va?',
'preciso de um médico': 'j\'ai besoin d\'un médecin',
'não estou me sentindo bem': 'je ne me sens pas bien',
'você tem algum problema?': 'vous avez un problème?',
'estou perdido': 'je suis perdu',
'preciso de um café': 'j\'ai besoin d\'un café',
'você tem café?': 'vous avez du café?',
'eu prefiro chá': 'je préfère le thé',
'passe-me o sal': 'passez-moi le sel',
'passe-me o açúcar': 'passez-moi le sucre',
'me dá um copo de água': 'donne-moi un verre d\'eau',
'onde posso comprar isso?': 'où puis-je acheter ça?',
'quanto custa isso?': 'combien ça coûte?',
'está em promoção?': 'est-ce en promotion?',
'quero comprar isso': 'je veux acheter ça',
'isso é muito caro': 'c\'est très cher',
'isso está barato': 'c\'est pas cher',
'tem algo mais barato?': 'y a-t-il quelque chose de moins cher?',
'está em oferta?': 'est-ce en solde?',
'isso é incrível!': 'c\'est incroyable!',
'o que você está fazendo?': 'que faites-vous?',
'o que aconteceu?': 'que s\'est-il passé?',
'onde você vai?': 'où vas-tu?',
'eu vou para a escola': 'je vais à l\'école',
'eu vou para o trabalho': 'je vais au travail',
'estou esperando alguém': 'j\'attends quelqu\'un',
'qual é a sua comida favorita?': 'quel est ton plat préféré?',
'minha comida favorita é': 'mon plat préféré est',
'eu adoro pizza': 'j\'adore la pizza',
'estou assistindo TV': 'je regarde la télévision',
'qual é o seu passatempo?': 'quel est ton passe-temps?',
'meu passatempo é ler': 'mon passe-temps est de lire',
'você gosta de viajar?': 'aimes-tu voyager?',
'eu adoro viajar': 'j\'adore voyager',
'estou aprendendo inglês': 'j\'apprends l\'anglais',
'não tenho prisa': 'je n\'ai pas de précipitation',
'eu estou muito ocupado': 'je suis très occupé',
'eu preciso de descanso': 'j\'ai besoin de repos',
'eu estou perdido': 'je suis perdu',
'me ajuda por favor': 'aide-moi s\'il te plaît',
'me passa um copo de água': 'passe-moi un verre d\'eau',
'você quer?': 'tu veux?',
'não entendi o que você disse': 'je n\'ai pas compris ce que tu as dit',
'pode me ensinar mais?': 'tu peux m\'apprendre plus?',
'eu não tenho tempo': 'je n\'ai pas le temps',
'estou esperando a minha vez': 'j\'attends mon tour',
'onde podemos nos encontrar?': 'où pouvons-nous nous rencontrer?',
'você gosta de futebol?': 'aimes-tu le football?',
'gostei muito!': 'j\'ai beaucoup aimé!',
'me avise quando chegar': 'préviens-moi quand tu arrives',
'onde fica o supermercado?': 'où est le supermarché?',
'eu estou indo para a casa': 'je vais à la maison',
'você está com fome?': 'tu as faim?',
'você está com sede?': 'tu as soif?',
'eu vou para o trabalho agora': 'je vais au travail maintenant',
};
  
  
  